---
title: '*Analytics* -  Documentação técnica'
---


```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# Remove scientific notation
options(scipen=999, warn = -1)
```

___

**Atenção, esta página foi criada pela equipe de Dados da Tembici.**

___

O objetivo desta página é apresentar informações sobre as técnicas utilizadas e explicações acerca dos testes estatísticos, modelos de *machine learning* e processamento de linguagem natural utilizados nos projetos de análise de dados. Esta documentação está classificada por assunto abordado.

# Documentos 

Neste momento existem 3 (três) documentos online com as informações separadas por problemas de negócio, conforme descrito a seguir.


No documento de "<a href="https://rsaviovieira.github.io/apendice_teste/public/hipoteses.html" target="_blank">Teste de Hipóteses</a>" são apresentadas as informações sobre os testes estatísticos aplicados pela equipe de Dados da Tembici nos relatórios de hipóteses realizados. 

No documento de "<a href="https://rsaviovieira.github.io/apendice_teste/public/ml.html" target="_blank">*Machine Learning*</a>" são detalhados os algoritmos utilizados pela equipe para a aplicação da etapa de predição aos problemas de negócio. 

No documento de "<a href="https://rsaviovieira.github.io/apendice_teste/public/text_mining.html" target="_blank">*Text Mining*</a>" é apresentada a técnica de processamento de Linguagem Natural, utilizada pela equipe de *People Analytics* para transformação de textos em dados para a análise. 